/*
 * Copyright (C) 2010-2018 Gordon Fraser, Andrea Arcuri and EvoSuite
 * contributors
 *
 * This file is part of EvoSuite.
 *
 * EvoSuite is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3.0 of the License, or
 * (at your option) any later version.
 *
 * EvoSuite is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with EvoSuite. If not, see <http://www.gnu.org/licenses/>.
 */
package org.evosuite.buildsupport;

import org.apache.commons.io.FileUtils;
import org.apache.maven.it.Verifier;
import org.apache.tools.ant.DefaultLogger;
import org.apache.tools.ant.Project;
import org.apache.tools.ant.ProjectHelper;
import org.evosuite.runtime.InitializingListener;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Make sure that tests generated by EvoSuite can be run from different build tools.
 * In particular, here we are interested to see if instrumentation is properly done.
 *
 * Note: the tests do not have instrumentation code, and so they will pass only if
 * JUnit listener does it
 */
public class BuildSupportIT {

    private final Path simple = Paths.get("projects","simple");
    private final Path extension = Paths.get("projects","extension");

    private String getEvoSuiteVersion(){
        //update version if run from IDE instead of Maven
        return System.getProperty("evosuiteVersion","1.2.1-SNAPSHOT");
    }

    @BeforeEach
    public void setUp() throws Exception {
        bootstrapEvoSuiteArtifactsInFixtureRepo(simple);
        bootstrapEvoSuiteArtifactsInFixtureRepo(extension);
        cleanProjects();
    }

    @AfterEach
    public void clean() throws Exception {
        cleanProjects();
    }

    private void cleanProjects() throws Exception {
        Verifier maven = getMaven(simple);
        maven.executeGoal("clean");

        FileUtils.deleteQuietly(simple.resolve("log.txt").toFile());
        FileUtils.deleteQuietly(simple.resolve(InitializingListener.getScaffoldingListFilePath()).toFile());
        FileUtils.deleteQuietly(simple.resolve("build").toFile());

        Verifier extensionMaven = getMaven(extension);
        extensionMaven.executeGoal("clean");
        FileUtils.deleteQuietly(extension.resolve("log.txt").toFile());
        FileUtils.deleteQuietly(extension.resolve(InitializingListener.getScaffoldingListFilePath()).toFile());
    }

    private void bootstrapEvoSuiteArtifactsInFixtureRepo(Path projectPath) throws Exception {
        Path projectRoot = Paths.get("").toAbsolutePath().normalize();
        Path repoRoot = projectRoot.getParent().getParent();
        if (repoRoot == null) {
            throw new IllegalStateException("Could not resolve repository root from " + projectRoot);
        }

        Path localRepo = projectPath.resolve(".m2").resolve("repository").toAbsolutePath();

        Verifier bootstrapRuntimeAndPlugin = new Verifier(repoRoot.toString());
        bootstrapRuntimeAndPlugin.setAutoclean(false);
        bootstrapRuntimeAndPlugin.setLocalRepo(localRepo.toString());
        bootstrapRuntimeAndPlugin.setCliOptions(Arrays.asList(
                "-pl", "runtime,plugins/maven",
                "-am",
                "-DskipTests",
                "-DskipITs",
                "-Dcheckstyle.skip=true",
                "-Denforcer.skip=true",
                "-Dmaven.javadoc.skip=true",
                "-Dlicense.skip=true",
                "-Dspotbugs.skip=true"
        ));
        bootstrapRuntimeAndPlugin.executeGoal("install");

        // Build standalone runtime from a clean module target to avoid stale shaded classes.
        Verifier bootstrapStandaloneRuntime = new Verifier(repoRoot.toString());
        bootstrapStandaloneRuntime.setAutoclean(false);
        bootstrapStandaloneRuntime.setLocalRepo(localRepo.toString());
        bootstrapStandaloneRuntime.setCliOptions(Arrays.asList(
                "-pl", "standalone_runtime",
                "-DskipTests",
                "-DskipITs",
                "-Dcheckstyle.skip=true",
                "-Denforcer.skip=true",
                "-Dmaven.javadoc.skip=true",
                "-Dlicense.skip=true",
                "-Dspotbugs.skip=true"
        ));
        bootstrapStandaloneRuntime.executeGoals(Arrays.asList("clean", "install"));
    }

    @Test
    public void testMaven() throws Exception{
        Verifier maven = getMaven(simple);
        maven.executeGoal("test");
        maven.verifyTextInLog("Running com.testbuild.support.FooTest");
        maven.verifyTextInLog("Tests run: 3, Failures: 0, Errors: 0, Skipped: 0");
        assertTrue(simple.resolve(InitializingListener.getScaffoldingListFilePath()).toFile().isFile());
    }

    @Test
    public void testMavenExtensionMode() throws Exception {
        Verifier maven = getMaven(extension);
        maven.executeGoal("test");
        maven.verifyTextInLog("Running com.testbuild.extension.Foo_ESTest");
        maven.verifyTextInLog("Tests run: 1, Failures: 0, Errors: 0, Skipped: 0");

        Path scaffoldingList = extension.resolve(InitializingListener.getScaffoldingListFilePath());
        assertTrue(scaffoldingList.toFile().isFile());
        String content = new String(Files.readAllBytes(scaffoldingList), StandardCharsets.UTF_8).trim();
        assertTrue(content.isEmpty(), "Expected no scaffolding entries for extension-mode fixture");
    }


    @Disabled("Pass from IDE, but fail from Maven")
    @Test
    public void testAnt() throws Exception{

        /*
            Getting Ant to work is a mess :(
            No wonder no one is really using it anymore...

            This test passes on IDE, but fail when executed from Maven.
            Failed to try to get it work, as Ant as so many bugs and weird,
            counter-intuitive behaviors...

            A possible solution would be to call an external Ant from a spawn
            process. Doable, but overcomplicated, as anyway having such test
            in our Jenkins is not critical, ie breaking support for Ant
            is not so critical as it would be for Maven and Gradle.
         */

        Project project = new Project();
        project.setBasedir("projects/simple");

        project.setUserProperty("evosuiteVersion",getEvoSuiteVersion());
        //the setBasedir simply does not work, so need to re-define paths here :(
        project.setUserProperty(InitializingListener.COMPILED_TESTS_FOLDER_PROPERTY, "projects/simple/build/tests");
        //project.setUserProperty("mavenAntTasksCP","projects/simple/lib/maven-ant-tasks-2.1.3.jar");
        project.setUserProperty("mavenAntTasksCP","lib/maven-ant-tasks-2.1.3.jar");

        project.setUserProperty("compile.fork","false");
        project.init();

        Path buildFile = simple.resolve("build.xml");
        ProjectHelper.configureProject( project, buildFile.toFile());


        ByteArrayOutputStream errBuffer = new ByteArrayOutputStream();
        ByteArrayOutputStream outBuffer = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(errBuffer);
        PrintStream err = new PrintStream(outBuffer);

        DefaultLogger consoleLogger = new DefaultLogger();
        consoleLogger.setErrorPrintStream(err);
        consoleLogger.setOutputPrintStream(out);
        consoleLogger.setMessageOutputLevel(Project.MSG_INFO);
        project.addBuildListener(consoleLogger);

        String phase = "clean";
        try {
            project.executeTarget(phase);
            phase = "compile";
            project.executeTarget(phase);
            phase = "compile-tests";
            project.executeTarget(phase);
            phase = "test";
            project.executeTarget(phase);
        } catch (Exception e){
            String res = outBuffer.toString()+"\n" + errBuffer.toString();
            throw new RuntimeException("Failed to execute Ant on phase '"+phase+"': "+e.getMessage()+"\nLOGS:\n"+res, e);
        }

        String res = outBuffer.toString()+"\n" + errBuffer.toString();

        assertTrue(res.contains("[junit] Testcase: testInstrumentation took"), res);
        assertTrue(res.contains("[junit] Testcase: testDoesFileExist_deactivatedInstrumentation took"), res);
        assertTrue(res.contains("[junit] Testcase: testDoesFileExist_withInstrumentation took"), res);
    }



    private Verifier getMaven(Path targetProject) throws Exception{
        Verifier verifier  = new Verifier(targetProject.toAbsolutePath().toString());
        verifier.setLocalRepo(targetProject.resolve(".m2").resolve("repository").toAbsolutePath().toString());
        Properties props = new Properties(System.getProperties());
        props.put("evosuiteVersion", getEvoSuiteVersion());
        verifier.setSystemProperties(props);
        return verifier;
    }

}
